### ISSUE TITLE
Add support for Chef feat

### ISSUE THREAD

**Issue by esteele** [Haxxer/FoundryVTT-ShortRestRecovery#1]
One of my players wants to take the chef feat, so I’d appreciate support for that. It adds an extra 1d8 of healing at the end of a rest, similar to Song of Rest , but without the level scaling. https://5e.tools/feats.html#chef_tce

**Comment by Haxxer** [comment]
So it heals the party for 1d8 hit points, provided they have Chef's tools and ingredients at hand. Is ingredients something we should worry about?

**Comment by Haxxer** [comment]
Added in 0.3.0

**Comment by esteele** [comment]
Thank you!
