### ISSUE TITLE
Can't use hit dice in Foundry 0.8.6

### ISSUE THREAD

**Issue by DylanAngell** [Haxxer/FoundryVTT-ShortRestRecovery#2]
The short rest dialog says "1 remaining" no matter how many hit dice are actually available. Attempting to roll give the error message "[Actor Name] has no available d6 Hit Dice remaining!" The dropdown box still shows "1 available" when this happens.

Song of Rest and the Chef feat both successfully activate, but no hit dice are actually rolled and the only hit points recovered are from SoR & Chef.

**Comment by Haxxer** [comment]
Thanks for the report, I'll be looking into updating this to 0.8.x this coming weekend.

**Comment by Haxxer** [comment]
Fixed with the latest release, please update your module :)
