### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by DarKDinDoN** [Haxxer/FoundryVTT-ShortRestRecovery#5]
Hello,

For players not using the english translation, would you mind searching the correct strings within the name of an item rather than making it a strict comparison?
This way we could keep the translated name and have the english within parentheses like : xxxxxxxxxxxx (arcane recovery)

Thx!

**Comment by Haxxer** [comment]
Certainly, I'll add support for that in the next update

**Comment by Haxxer** [comment]
Fixed in 0.4.2
