### ISSUE TITLE
Add compatibility with Long Rest Hit Dice Healing

### ISSUE THREAD

**Issue by TheRarita** [Haxxer/FoundryVTT-ShortRestRecovery#6]
Please, it would be great if you could make this compatible with https://github.com/schultzcole/FVTT-Long-Rest-HD-Healing-5e which changes long rest to also roll hit dies but those still have the pop-up.

**Comment by Haxxer** [comment]
What would you like to happen when you roll hit dice on a long rest? Would you still expect to get bonuses from Song of Rest and Chef?

**Comment by TheRarita** [comment]
Since both specify only short rest I would say no, but if it is not too much bother it maybe could bet setup-able in mod configuration?

**Comment by Haxxer** [comment]
Fixed in 0.4.2
