### ISSUE TITLE
conflict with dnd helpers module

### ISSUE THREAD

**Issue by SR5060** [Haxxer/FoundryVTT-ShortRestRecovery#8]
![image](https://user-images.githubusercontent.com/85184490/134699901-4165b243-8106-48fd-867a-1ecbba1a9ad7.png)

appears to disable most/all of the short rest recovery features. this has been posted on that module as well

**Comment by trioderegion** [comment]
For reference: https://github.com/trioderegion/dnd5e-helpers/issues/192

**Comment by Haxxer** [comment]
Closing as per dnd5e helpers' ticket

**Comment by SR5060** [comment]
Ah sorry, forgot to close this one out
